testScores = read.csv("http://www.math.mcgill.ca/yyang/regression/data/TestScores.csv", header=TRUE)
testScores$Faculty = as.factor(testScores$Faculty)
fit.testScores = lm(testScores$Score ~ testScores$Faculty)
summary(fit.testScores)
anova(fit.testScores)
